schedules:
- cron: "10 22 * * *"
  displayName: Master nightly build
  branches:
    include:
    - master
  always: true
variables:
  newest_zivid_version: '1.5.0+63f281e2-26'
stages:
  - stage: Code_Analysis
    jobs:
    - job: Code_Analysis
      pool:
        vmImage: ubuntu-16.04
      steps:
      - script: 'CI_TEST_OS=ros:melodic-ros-base-bionic ./continuous-integration/run_code_analysis_in_docker.sh'
  - stage: Build_And_Test_Newest_Zivid_Melodic
    jobs:
    - template: continuous-integration/azure-pipelines/templates/build_and_test.yml
      parameters:
        zivid_versions: ["${{ variables['newest_zivid_version'] }}"]
        ros_distros: ['ros:melodic-ros-base-bionic']
        compilers: ['g++-7', 'g++-8', 'g++-9', 'clang++-7']
  - stage: Build_And_Test_Newest_Zivid_Kinetic
    jobs:
    - template: continuous-integration/azure-pipelines/templates/build_and_test.yml
      parameters:
        zivid_versions: ["${{ variables['newest_zivid_version'] }}"]
        ros_distros: ['ros:kinetic-ros-base-xenial']
        compilers: ['g++-7']
  - stage: Build_And_Test_Old_Zivid_Melodic_And_Kinetic
    jobs:
    - template: continuous-integration/azure-pipelines/templates/build_and_test.yml
      parameters:
        zivid_versions: ['1.3.0+bb9ee328-10', '1.4.0+956f554d-12']
        ros_distros: ['ros:melodic-ros-base-bionic', 'ros:kinetic-ros-base-xenial']
        compilers: ['g++-7']
