zivid_camera:
  ros__parameters:
    zivid:
      camera:
        frame_id: "map"
        settings_path: "/home/grans/dev_ws/src/zivid-ros/zivid_camera/config/zivid_camera_settings.yml"
        settings2d_path: "/home/grans/dev_ws/src/zivid-ros/zivid_camera/config/zivid_camera_settings2d.yml"
