__version__:
  serializer: 1
  data: 4
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 4.80645685
        Brightness: 1
        ExposureTime: 8333
        Gain: 1.09804174710977
        Patterns:
          Sine:
            Bidirectional: no
    - Acquisition:
        Aperture: 3.28882924
        Brightness: 1
        ExposureTime: 8333
        Gain: 1.82168709619691
        Patterns:
          Sine:
            Bidirectional: no
    - Acquisition:
        Aperture: 2.44367983
        Brightness: 1
        ExposureTime: 8333
        Gain: 3.3073735098601
        Patterns:
          Sine:
            Bidirectional: no
    - Acquisition:
        Aperture: 2.61632139
        Brightness: 0.999999999999999
        ExposureTime: 24999
        Gain: 4.23762147263063
        Patterns:
          Sine:
            Bidirectional: no
  Processing:
    Color:
      Balance:
        Blue: 1
        Green: 1
        Red: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: no
            Strength: 0.4
          Removal:
            Enabled: no
            Threshold: 0.5
      Noise:
        Removal:
          Enabled: yes
          Threshold: 7
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 5
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1.5